# Generated by Django 4.1 on 2022-10-29 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("keuangan", "0002_cashout"),
        ("keuangan", "0003_alter_cashout_approved_alter_cashout_disbursed"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("keuangan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cashout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("approved", models.BooleanField(default=False)),
                ("disbursed", models.BooleanField(default=False)),
                (
                    "uang_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="keuangan.keuanganadmin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
