# Generated by Django 4.1 on 2022-10-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0002_cashout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashout",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cashout",
            name="disbursed",
            field=models.BooleanField(default=False),
        ),
    ]
