# Generated by Django 4.1 on 2022-11-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
