# Generated by Django 4.1 on 2022-11-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_alter_feedback_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_feedback',
            new_name='your_feedback',
        ),
    ]
