# Generated by Django 4.1 on 2022-10-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipsAndTrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('published_date', models.DateField()),
                ('brief_description', models.TextField()),
                ('url_image', models.CharField(max_length=500)),
                ('url_article', models.CharField(max_length=500)),
            ],
        ),
    ]
