# Generated by Django 4.1 on 2022-10-31 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjemputan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(max_length=100)),
                ('tanggal_jemput', models.CharField(max_length=30)),
                ('waktu_jemput', models.TimeField(blank=True, null=True)),
                ('waktu_sekarang', models.DateTimeField(auto_now_add=True)),
                ('jenis_sampah', models.CharField(max_length=30)),
                ('berat_sampah', models.IntegerField()),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
