name: Test

on:
  push:
    # testing for main is done on PR
    branches-ignore:
      - main

jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        cache: 'pip'
        python-version-file: '.python-version'
    - name: Install needed packages
      run: |
        pip install -r requirements.txt
        pip install coverage
    - name: Collect staticfiles
      run: python manage.py collectstatic --no-input
    - name: Run unit tests
      run: |
        coverage run --omit="manage.py" manage.py test
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: unittest-coverage
        path: .coverage*
    - name: Generage coverage report
      run: |
        coverage report -m
        coverage html
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: unittest-coverage-html
        path: htmlcov/