name: Test

on:
  pull_request:
    # test before merge to main
    branches:
      - main
  push:
    # testing for main is done on PR
    branches-ignore:
      - main

jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.10.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Install needed packages
      run: |
        pip install -r requirements.txt
        pip install coverage
    - name: Collect staticfiles
      run: python manage.py collectstatic --no-input
    - name: Run unit tests
      run: |
        python manage.py test
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: unittest-coverage
        path: .coverage*